name: tclock

version: '1.0'

summary: TerminalClock

description: 'Terminal Clock: A large digital clock that runs in a terminal.'

confinement: devmode

base: core18

parts:
  tclock:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
    - python-six

apps:
  tclock:
    command: ./main.py